services:
  # PostgreSQL
  postgres_db:
    image: postgres:15-alpine
    container_name: healmata_backend_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5433:5432" # access DB from local through DBeaver/DataGrip
    volumes:
      - pgdata:/var/lib/postgresql/data # permanent data storage; data is not lost when the container is deleted
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Migration (run Goose)
  db_migration:
    image: golang:1.26.4-alpine
    container_name: healmata_backend_migration
    # bring migrations files from local to container
    volumes:
      - ./internal/db/migrations:/migrations
    command: >
      /bin/sh -c "
      go install github.com/pressly/goose/v3/cmd/goose@latest && 
      goose -dir /migrations postgres 'postgres://${DB_USER}:${DB_PASSWORD}@postgres_db:5432/${DB_NAME}?sslmode=${DB_SSLMODE}' up"
    depends_on:
      postgres_db:
        condition: service_healthy # run migration only when DB is ready (passed healthcheck)

  # golang app service
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: healmata_backend_api
    restart: on-failure
    ports:
      - "8080:8080" # mapping APP_PORT to outside
    env_file:
      - .env
    environment:
      - DB_HOST=postgres_db
    depends_on:
      postgres_db:
        condition: service_healthy
      db_migration:
        condition: service_completed_successfully # start API only when migration completed running

volumes:
  pgdata: # declare volume for DB